name: Netlify

on:
  push:
    branches:
      - "main"
      - master
    # Pattern matched against refs/tags
    tags:
      - "*" # Push events to every tag not containing /
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: netlify
    steps:
      - uses: actions/checkout@v5

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: pnpm

      - run: pnpm install

      - run: pnpm build
        env:
          NETLIFY_BUILD: "true"
          DATABASE_URL: ${{ secrets.NETLIFY_DB_URL_PROD }}

      - name: Install Netlify
        run: pnpm install netlify-cli@23.7.3 -g

      - name: Deploy to Netlify
        id: netlify_deploy
        #if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        run: |
          netlify deploy \
            --prod \
            --site ${{ secrets.NETLIFY_SITE_ID_PROD }} \
            --auth ${{ secrets.NETLIFY_TOKEN }}
        env:
          DATABASE_URL: ${{ secrets.NETLIFY_DB_URL_PROD }}
